### ISSUE TITLE
The VS code Shiny extension for python never loads the app with large datasets. 

### ISSUE THREAD

**Issue by Oscarhg42** [posit-dev/shiny-vscode#62]
The extension never loads the app correctly when working with large data sets. No error message is given, it just stops after the message `INFO:     Application startup complete.` 

I'm loading a pandas dataframe with 520 rows and 20 columns. When I take only 10 rows from the original data set, the app loads fine.

![image](https://github.com/posit-dev/shiny-vscode/assets/13757679/39c03049-0505-456c-9e02-b4ba89d482f6)

**Comment by jcheng5** [comment]
Does it take more than 10 seconds for the app to load? If so it’s probably this line, that gives up after 10 seconds: https://github.com/posit-dev/shiny-vscode/blob/80560bf36d516ff89dffe88bd9a28cee9edd4d43/src/net-utils.ts#L54 I think I did it this way because the extension has no way of knowing if the app succeeded or failed to launch, and I didn’t want it to keep waiting on that port forever (imagine that launch window suddenly popping up way down the line).

Maybe it should never time out, but each new attempt to launch should cancel all previous attempts? Or we could simply increase the timeout to something more conservative—10sec is pretty stingy.

**Comment by Oscarhg42** [comment]
yes, it takes more than 10 seconds to load the dataset and extracting only 10 rows. The thing is that I'm connecting to a databricks server so the connection and loading takes a little bit of time

**Comment by Oscarhg42** [comment]
If I restrict the query to only get 10 rows from source instead of having the entire data set, then the query takes less than 10 seconds approx and the app does load

**Comment by gadenbuie** [comment]
> Maybe it should never time out, but each new attempt to launch should cancel all previous attempts? Or we could simply increase the timeout to something more conservative—10sec is pretty stingy.

We close existing `Shiny` terminals with a new launch attempt (a new click on the Play button, not an auto-reload), which I imagine would have the same affect as cancelling previous attempts, right? In which case, upping the timeout is more reasonable.

We could also do something like wait 15 seconds and then ask the user via a dialog box if they want to keep waiting or kill the app.

**Comment by jcheng5** [comment]
@gadenbuie Killing the console would prevent multiple Shiny processes from starting, but I don’t think it will stop openBrowserWhenReady—oooh but maybe that’s the ideal fix. openBrowserWhenReady can be notified or can query whether its owning terminal is still open, and if not, don’t open the browser. What do you think?

**Comment by gadenbuie** [comment]
@olivroy How long does your app take to start up?

**Comment by gadenbuie** [comment]
Thanks... so right now we show this message because sometimes an app takes a very long time to start up and other times it fails immediately. The problem in the immediate failure case is that the process for watching for the port that indicates that app is running won't know that the app failed to start up. 

So any increase in the delay means someone who's app didn't start because of an immediate failure. On the whole, making the delay configurable is an easy "fix", but I'd rather spend time finding another pattern for starting up apps that can differentiate between immediate issues and startup delays.

If you have the time an inclination to submit a PR, we'd very likely take the additional feature!
