### ISSUE TITLE
Cannot open the external Shiny webpage.

### ISSUE THREAD

**Issue by Jxuanrui** [posit-dev/shiny-vscode#76]
![image](https://github.com/user-attachments/assets/b76b8a81-2d2e-46f2-990e-00d42a0a4680)
Hello, this is my first time using the VS Code Shiny extension, and I've encountered a problem. When I use it, the Shiny preview window that automatically pops up in VS Code does not navigate to the URL. I can manually enter it and it works, but I'd like to know how to make it navigate automatically. Is there something wrong with my settings?

**Comment by gadenbuie** [comment]
Sorry to hear that @Jxuanrui. Is there anything printed in the terminal window opened by the extension (it's named "Shiny")?

**Comment by Jxuanrui** [comment]
Yes, I tried switching to another computer and then used R to start Shiny. The same issue occurred: a URL appeared in the terminal, and I could access the Shiny interface by copying the URL into the browser. However, the VSCode extension does not automatically redirect to the Shiny interface.
![image](https://github.com/user-attachments/assets/54b8c968-d1f9-408d-a087-a1dd711852d2)

**Comment by gadenbuie** [comment]
Thanks @Jxuanrui. Does your app take a long time to start normally? The error message in the bottom right is shown when it takes longer than 10s to start the app. From the state shown in your screenshot, you should be able to click "Keep waiting", at which point the preview will open immediately because the app has already started. Alternatively, you could dismiss the error message and Ctrl + Click on the URL in the terminal to open the preview.

**Comment by Jxuanrui** [comment]
Alright, maybe there are still some errors in my software settings. Thank you for your suggestion.
